### ISSUE TITLE
Poll re: possible shift from fortnightly to monthly

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#120]
See discussion here: http://ircbot.responsiveimages.org/bot/log/respimg/2015-01-12#T107999

**Comment by eeeps** [comment]
https://docs.google.com/forms/d/1c_pQqkwOhBYe3mD5gBAEXscZDeA2bQyhL_NiW-mYpC4/viewform?usp=send_form

**Comment by Wilto** [comment]
Oh, good idea having the “unsubscribe” option in there. You never know.
