### ISSUE TITLE
Dave Newton researching ImageMagick-backed-backends for resizing

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#136]
https://twitter.com/newtron/status/562289866525114369

**Comment by nwtn** [comment]
Can you ping me about this before the newsletter goes out? Depending on where I'm at, I may want to hold off until the next one before putting this out in the wild.

**Comment by eeeps** [comment]
Will do! Out of curiosity, is it for this talk:

http://www.meetup.com/Toronto-Web-Performance-Group/events/220287399/

Or a future article? Both (hopefully!)?

**Comment by nwtn** [comment]
Both!

**Comment by eeeps** [comment]
Something like:

> Dave Newton has constructed a [massive set of tests](https://github.com/nwtn/image-resize-tests) for all of ImageMagick’s compression and conversion knobs. These tests are the raw material for an upcoming [talk](http://www.meetup.com/Toronto-Web-Performance-Group/events/220287399/) and article on the subject – can’t wait!

?
