### ISSUE TITLE
Converting the Blink respimg tests to W3C tests

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#147]
http://ircbot.responsiveimages.org/bot/log/respimg/2015-02-12#T113237

I'll admit: I barely know what that means.

Where do Blink's layout tests live?

Are they getting ported to https://github.com/w3c/web-platform-tests ?

URLs?

**Comment by yoavweiss** [comment]
[LayoutTests](https://chromium.googlesource.com/chromium/blink/+/master/LayoutTests/)

They're not getting ported to web-platform-tests wholesale, but there is an effort to use the same JS framework as web-platform-tests (called testharness.js).
The main hurdle is that many of the LayoutTests (especially for srcset) rely on internal non-standard APIs for testing. That can't be ported over to w3c tests without first standardizing these internal APIs.

Then, a lot of the srcset tests are testing resource loading logic, which is UA specific, so can't be ported over.
