### ISSUE TITLE
Wordpress decides on a default sizes

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#154]
(for now)

https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/51

Settable by theme authors:
https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/30

And over-rideable by site maintainers via a `data-sizes` attribute on a per-image basis.

Neat.

**Comment by joemcgill** [comment]
FWIW, I'm still tinkering with the best method for theme authors to override the defaults for images embedded in HTML content.
