### ISSUE TITLE
newtron all-in-one Grunt respimg plugin

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#156]
https://github.com/nwtn/grunt-respimg

It SVGs, it PNGs, it `srcset`s, it `sizes` (does it `picture media`??)...

Basically all of the best things about [all](https://github.com/andismith/grunt-responsive-images) [of](https://github.com/dbushell/grunt-svg2png) [the](https://github.com/JamieMason/grunt-imageoptim) [best](https://github.com/sindresorhus/grunt-svgmin) Grunt resp/img plugins rolled into one, along with [Dave’s thoroughly-researched ImageMagick settings](https://github.com/nwtn/image-resize-tests).

**Comment by nwtn** [comment]
It's not doing any art direction, just resizing, and right now no HTML output (though I might like to add that soon).

I'll probably push it to npm today, so you'll want to update the URL once that happens.

**Comment by eeeps** [comment]
https://www.npmjs.com/package/grunt-respimg

**Comment by nwtn** [comment]
https://www.npmjs.com/package/grunt-respimg

**Comment by nwtn** [comment]
heh. you beat me by 28 seconds.

**Comment by eeeps** [comment]
(: http://media.giphy.com/media/2CcKiHPDsJqVi/giphy.gif
