### ISSUE TITLE
Picturefill/WP Slack

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/newsletters#188]
Any interest in lurking in those for the sake of newsletter fodder, @eeeps?

**Comment by eeeps** [comment]
Slack, you say... *strokes chinbeard*. Sounds fun. Gotta sign up for an account brb

**Comment by eeeps** [comment]
username: eeeps
email: e@ericportis.com

Do I get invited or do I find you guys or what?

**Comment by Wilto** [comment]
https://pf-slackin.herokuapp.com/ for Picturefill, https://make.wordpress.org/chat/ for WP (channel is #feature-respimg)
