### ISSUE TITLE
`w` and `sizes` in WebKit nightly

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#193]
http://nightly.webkit.org/

Test please!

Do I remember hearing something about how this is in, now, for testing, but might be removed in the future?

**Comment by yoavweiss** [comment]
Currently the feature is behind a build flash in WebKit. We want to remove
the flag, to increase the chances of it being in the stable branch. In
order to do that, we need moar testing!

**Comment by yoavweiss** [comment]
And the flag is no more https://bugs.webkit.org/show_bug.cgi?id=144679
