### ISSUE TITLE
Newtron becomes a core firefox committer

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#195]
(going to sit on this one until it lands)

APNG mime ftw

What's the best link to use?

**Comment by marcoscaceres** [comment]
heh ... don't forget to mention that "Yoav now obsolete, retires to Bahamas to spend all that RICG moneys!".

**Comment by eeeps** [comment]
I'll be sure to!

Here's a link: https://bugzilla.mozilla.org/show_bug.cgi?id=1160200
