### ISSUE TITLE
PSA: Firefox 38 w/ respimg support ships TOMORROW

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#196]
Where tomorrow = Tuesday, May 12th

It includes everything (`srcset`, `x`, `w`, `sizes`, `picture`, `type`, and `media`) but doesn't respond to viewport changes... yet. v39 (which is slated for June 30th) should.

**Comment by Wilto** [comment]
I _think_ we’re looking at even sooner than that, per https://bugzilla.mozilla.org/show_bug.cgi?id=1135812

![image](https://cloud.githubusercontent.com/assets/439942/7544443/15496fa6-f59b-11e4-9689-3ac66a8e0254.png)

@miketaylr, that look right to you?

**Comment by miketaylr** [comment]
Might could be yeah, depending on how soon those patches land.
