### ISSUE TITLE
Newtron speaks

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#199]
https://speakerdeck.com/newtron/improving-performance-with-responsive-and-responsible-images-openwest
https://speakerdeck.com/newtron/universal-web-design-how-to-create-an-awesome-experience-for-every-user-openwest

https://2015.cssconf.com/#speakers

**Comment by nwtn** [comment]
Also http://opensourcebridge.org/sessions/1665 but, like one of the openwest ones, it's not really respimgy.
