### ISSUE TITLE
“Update Picturefill” redux

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/newsletters#209]
Could we include another little blurb about upgrading to Picturefill 2.3.1+? https://bugs.webkit.org/show_bug.cgi?id=144095 is _bad news_, and I’m a little worried that a few more of these will mean `currentSrc` getting scratched out of native implementations.

**Comment by marcoscaceres** [comment]
Tragic :( What's the larger takeaway here, @Wilto, wrt prollyfilling features? What should have been done differently in picture fill to avoid this?

**Comment by yoavweiss** [comment]
I think that the main take-away is not to use feature-detection of one part of the feature to assume other parts of the features are there (or not there in this case).

**Comment by marcoscaceres** [comment]
ok, so it's basically the classic `.hasFeature()` kind-of problem.

**Comment by Wilto** [comment]
Yeah; we (read: “I”) got spoiled, being so tuned-in to the real implementations. The “use Picturefill at all” test hinged on `picture` support—mostly unchanged since the first versions of Picturefill—and it worked fine so long as the support divide was “no respimg support,” “basic `srcset` support,” or “everything supported, including `picture`.”

WebKit/Edge doing `srcset`/`sizes` but no `picture` meant Picturefill was running anyway—which would be a minor thing, if that didn’t mean a `use strict` script trying to write to a read-only `currentSrc` property.  Then everything blows up.

**Comment by marcoscaceres** [comment]
@Wilto thanks for the clarification.

**Comment by marcoscaceres** [comment]
... and for breaking the internet :)

**Comment by Wilto** [comment]
“If I had a dollar,” y’know?

Anyway, I’m starting a _major_ “update your Picturefills” push. If you’ve got a rooftop you can shout about it from, please please please don’t hesitate to make some noise about this.

**Comment by marcoscaceres** [comment]
@Wilto, I recommend we blast maybe 3 times (stagger over a few days) on the respimg twitter account and hit the mailing list too.

**Comment by marcoscaceres** [comment]
Do we know anyone at ESPN? Any other majors we should be hitting up? Actually, never mind about that the mailing list - the news letter has got us covered there.

**Comment by eeeps** [comment]
I'll headline with it!

**Comment by eeeps** [comment]
Specifically, with this: https://css-tricks.com/please-update-picturefill/
