### ISSUE TITLE
Blink has a vision for element-level adaptive CSS, and it leans on JavaScript

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#217]
http://ircbot.responsiveimages.org/bot/log/respimg/2015-06-05#T132463

@tabatkins is this broadcast-able?
@wilto should it be broadcasted?

If anyone over at Blink is going to write this up, either on a blog or in a mailing list, I'd love to wait and link to that, rather than trying (and probably failing) to connect the dots[1] Tab outlined in the IRC myself.

[1] “ ‘resize events everywhere’ and ‘custom at-rules’ and maybe ‘contain: layout’ ”

**Comment by Wilto** [comment]
I think I’d like to hold off on making much noise about this this until we’ve started our “BE AWARE OF THE PROBLEM WE ARE LOOKING TO SOLVE” push. I had a bunch of stuff timed to jump off this week but it all kinda hinges on one big article, and that got bumped to a few weeks from now.

**Comment by eeeps** [comment]
Ok, I'll hold off on this for the time being.
