### ISSUE TITLE
WICG launch

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#234]
Web Incubator Community Group
https://www.w3.org/community/wicg/
http://wicg.io
Chaired by Marcos, Yoav, and Chris Wilson.

First impression, after seeing the initials: it's a Wario-RICG!

Second impression, after reading the charter: it’s a catch-all CG with a super-low barrier to entry, AKA a machine that turns GitHub repos into web standards.

The RICG and WICG share three letters, key people, and both pitch themselves as communities for web developers interested in standards, so I'm thinking I should say something to compare/contrast/clarify their relationship. Thoughts?

**Comment by marcoscaceres** [comment]
On Friday, July 3, 2015, eeeps <notifications@github.com> wrote:

> Web Incubator Community Group
> https://www.w3.org/community/wicg/
> http://wicg.io
> Chaired by Marcos, Yoav, and Chris Wilson.
>
> First impression, after seeing the initials: it's a Wario-RICG!
>
Omg we have a logo!


> Second impression, after reading the charter: it’s a catch-all CG with a
> super-low barrier to entry, AKA a machine that turns GitHub repos into web
> standards.
>
> The RICG and WICG share three letters, key people, and both pitch
> themselves as communities for web developers interested in standards, so
> I'm thinking I should say something to compare/contrast/clarify their
> relationship. Thoughts?
>
Happy to try to answer questions.

**Comment by aarongustafson** [comment]
I’m really excited about this new CG. I already have an experiment in the
works.

**Comment by marcoscaceres** [comment]
@eeeps we are still working out the details for the WICG group - in particular, exactly which parts the RICG will continue to handle and which parts the WICG would handle. Trying to set up a meeting with @Wilto on Tuesday so we can discuss. We are still working out all the details, but here is a **rough draft** of the announcement we hope to send out later this week: https://etherpad.mozilla.org/incubatorcg

@aarongustafson looking forward to seeing what you have.

**Comment by eeeps** [comment]
Asked and answered!
http://www.w3.org/blog/2015/07/wicg/#collaboration-with-the-ricg

**Comment by eeeps** [comment]
[Wilto](https://twitter.com/yoavweiss/status/618684921461239808) [writes](https://twitter.com/wilto/status/618880218049155072):

https://www.w3.org/community/respimg/2015/07/09/wicg/
