### ISSUE TITLE
Coming up on 1000 subscribers

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/newsletters#252]
Currently at 934. Worth calling out in a newsletter at some stage, I figure.

**Comment by eeeps** [comment]
Heck yeah!

Also: halfway to costing us money!?

**Comment by Wilto** [comment]
994

Wait, is that true? If we break 2000, I will _completely_ start payin’.

**Comment by Wilto** [comment]
1001!

**Comment by eeeps** [comment]
🎉!
