### ISSUE TITLE
Official respimg-in-WordPress Core proposal

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#253]
https://make.wordpress.org/core/2015/09/30/responsive-images-merge-proposal/

**Comment by joemcgill** [comment]
:+1:

**Comment by eeeps** [comment]
And here's the patch:
https://core.trac.wordpress.org/ticket/33641#comment:9

**Comment by joemcgill** [comment]
Merged: https://core.trac.wordpress.org/changeset/34855 :heart_eyes:
