### ISSUE TITLE
Chrome viewport bug(s)

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#255]
Keeps cropping up, so it seems worth mentioning.

http://terraling.github.io/srcset-sizes/
http://stackoverflow.com/questions/32941158/why-is-srcset-causing-images-to-download-multiple-times
http://stackoverflow.com/questions/32841724/picture-tag-uses-wrong-source-on-chrome-on-android
https://codereview.chromium.org/1337323003/
https://codereview.chromium.org/1346053002/

**Comment by yoavweiss** [comment]
Note that it's actually 2 different bugs. One fixed in M46 (yay), and one that I'm still working on...

**Comment by eeeps** [comment]
Ah, ok. So:

**First bug:** The Blink preloader used the device height as the viewport width when `width=device-width`. That one's fixed as of v46.

**Bug the second:** https://code.google.com/p/chromium/issues/detail?id=531820. On pages that *do not* have a `<meta name=viewport>` (or preload-scanner-visible `@viewport`), the preloader assumes that the viewport width = the device width. This is a problem on mobile Chromes, which, after the preloader is done, use a default viewport width of 980px when there's no author-set viewport width to use. So the preloader loads device-width-appropriate resources, and post-load, on the viewport resize to 980px, Chrome runs through and downloads the 980-px-appropriate resources. This is not yet fixed.

**Comment by yoavweiss** [comment]
exactly! I've missed the regular v47 window for that fix (which is surprisingly not trivial...) but I hope to have it fixed soon and merge it back to 47 before the beta gets too old.

**Comment by eeeps** [comment]
::thumbs up::
