### ISSUE TITLE
Yoav on Client Hints (and goats) at Velocity

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#263]
I think he's talking right this second. This issue is here to remind me track down slides, video, etc.

**Comment by eeeps** [comment]
http://velocityconf.com/devops-web-performance-ny-2015/public/schedule/detail/43854

**Comment by yoavweiss** [comment]
The talk was more about resource hints than client hints. In case it's still interesting for the newsletter, I'll post slides and video (when available) here

**Comment by yoavweiss** [comment]
Slides are on http://yoavweiss.github.io/velocity_nyc_resource_hints/
