### ISSUE TITLE
`picture` shipping in Safari betas

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#281]
https://twitter.com/RWD/status/686660388348411904

**Comment by eeeps** [comment]
Coming to Safari 9.1
https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_1.html

Too bad it double-downloads when multiple `source`s match the current environment >_<
http://jsbin.com/fikizogapu/1/edit?html,output

**Comment by yoavweiss** [comment]
Did someone file WebKit bugs on the double downloads?

**Comment by eeeps** [comment]
I sure didn't. But it looks like they might be fixed, now that I actually look at the test again?
